#!/usr/bin/env python3
"""Regenerate the translation stubs for built-in catalog names.

Run from the repository root after editing src/data/exercises.json:

    python3 tools/generate_catalog_names.py
"""

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SEED = ROOT / "src" / "data" / "exercises.json"
HEADER = (ROOT / "src" / "modules" / "exercisecatalog" / "infrastructure" / "seed"
          / "exercisecatalognames.h")
CONTEXT = "ExerciseCatalog"


def literal(text):
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    return f'QT_TRANSLATE_NOOP("{CONTEXT}", "{escaped}")'


def block(name, values):
    lines = [f"inline constexpr const char* {name}[] = {{"]
    lines += [f"    {literal(value)}," for value in values]
    lines.append("};")
    return "\n".join(lines)


def main():
    exercises = json.loads(SEED.read_text(encoding="utf-8"))["exercises"]

    names = [e["name"] for e in exercises]
    instructions = [e["instructions"] for e in exercises if e.get("instructions")]

    body = f"""// Generated by tools/generate_catalog_names.py -- do not edit by hand.
#pragma once

#include <QCoreApplication>
#include <QString>

namespace ExerciseCatalogNames
{{

{block("names", names)}

{block("instructions", instructions)}

inline QString translate(const QString& text)
{{
    return QCoreApplication::translate("{CONTEXT}", text.toUtf8().constData());
}}

}}
"""

    HEADER.write_text(body, encoding="utf-8")
    print(f"{HEADER.relative_to(ROOT)}: {len(names)} names, {len(instructions)} instructions")


if __name__ == "__main__":
    main()
